token="eyJhbGciOiJSUzI1NiIsImtpZCI6IjA2NWU1NWUxOGU4MWU2OGE3NTdhYzUyYTQxMzNjODczYWY5MTZiMjYifQ.eyJpc3MiOiJodHRwczovL2xhcHRvcC5sb2NhbC5pbzo1NTU0Iiwic3ViIjoiMTA4MjIxMTM1MDU3MjY4MDI5NzMyIiwiYXVkIjoiZXhhbXBsZS1hcHAiLCJleHAiOjE0ODIwMjMwNjgsImlhdCI6MTQ4MTkzNjY2OCwiZW1haWwiOiJrZXlvbGtAZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsIm5hbWUiOiLsoJXssKztm4gifQ.X-laHxp3zwzP-AVrwpTDQsXdnPqYOTq-m6UR2-15e3cuCQpxcwtMLTYRJwI_XAubROheUP-in4g7uBiLpTBMDKYnL2p8rDz2XFfuZz404iPavpzS2Z7rk3PSiohsjRaQEiskWWxXI6oXP8beITydTE9U7Ojgd2sgwsprwUe6LJF1uJLsz8ksi8avlazTV-zC3n0jrZfa7Zoc3cBD3YGDIp2zR5XyMVR0QVij20zO8vlz9smeJWGhD6D-3CTBQKOujyttzY6a7ZFbK8Z7qKeFTfcB6c38ct3psudPkMnO43Xdx9kOWgVihYm3IwMjFmM1L-Se5B5hb-fen1jGtuzrug"

curl --cacert ../../master/pki/kube-ca.pem -v -H "Authorization: Bearer $token" https://kube-apiserver.local.io/api/v1/nodes

#kubectl config set-credentials dex \
#  --token=$token
#
#kubectl config use-context dex-vagrant
#
#kubectl get node
#
