---
# Source: dex/templates/dex-app.yaml
apiVersion: v1
kind: Service
metadata:
  name: banking-goose-app
spec:
  type: NodePort    
  ports:
  - name: banking-goose-app
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30080      
  selector:
    app: banking-goose-app
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: banking-goose-app
  labels:
    app: banking-goose-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: banking-goose-app
    spec:
      containers:
      - name: banking-goose-app
        image: quay.io/keyolk/dex-app:0.0.1
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 80
        volumeMounts:
        - name: tls
          mountPath: /etc/dex/tls            

        env:
        - name: DEX_ISSUER
          value: https://kube-1.local.io:30443
        - name: DEX_CA
          value: /etc/dex/tls/tls.ca
        - name: DEX_CERT
          value: /etc/dex/tls/tls.cert
        - name: DEX_KEY
          value: /etc/dex/tls/tls.key            
        - name: DEX_APP_LISTEN_ADDRESS
          value: http://0.0.0.0:80
        - name: DEX_APP_REDIRECT_URI
          value: https://kube-1.local.io:30080/callback

        resources:
          limits:
            cpu: 512m
            memory: 200Mi
          requests:
            cpu: 512m
            memory: 200Mi

      volumes:
      - name: tls
        secret:
          secretName: banking-goose.tls            

---
# Source: dex/templates/dex.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: banking-goose
spec:
  type: NodePort    
  ports:
  - name: banking-goose
    protocol: TCP
    port: 443
    targetPort: 443
    nodePort: 30443    
  selector:
    app: banking-goose
---
apiVersion: v1
kind: Secret
metadata:
  name: banking-goose.tls
data:
  tls.ca: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURJRENDQWdpZ0F3SUJBZ0lVU3dZdkZORUc0cU1uVW0zWFNYcUFxNGk1NFBBd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0dqRVlNQllHQTFVRUF4TVBkbUZuY21GdWRDOXdhMmt2WkdWNE1CNFhEVEUyTVRJeE16QTBNVEV6TUZvWApEVEkyTVRJeE1UQTBNVEl3TUZvd0dqRVlNQllHQTFVRUF4TVBkbUZuY21GdWRDOXdhMmt2WkdWNE1JSUJJakFOCkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXAwNVR3b1BFNXUrQkxnQkxqY1VwWkhrcm5FRGgKc3loMUlQaU1iM3lzd09WSkVHOTE5eTFrVzlxNkVwSUpaYURac0JvRU9ERjNBQ2FyZFNyM0djTGZVOWZUS1J1VQplNThCK0doSS94WHVmVzJzTG9DY2RpbDJIREFMSFZWNW1TNWY3ZkVIazFadC9yKzczWXM2R25FcE9QQVoyUENWCkU5RGtVYStHVlB1SDZCUjdMalFYSnlqaGNEOFJIYW0vNHpNblFPMjZGNzRBZ1ZwYzd2eEpremFPcFhtT0Yram0KYnFtYnZIeWk5ZXN5aWowVk9VOWRoZjhVZE9zUFNBV095bENmRFc3RVBwR1VNVVJSTUlEWHZTSzFHZ2tNMlo2MgppL2ZiaXV6YnYxbDRoQmVaTW83dzN5ZDN6MXllTWhIYkNTRVd0MGVCT0pUTk5UaFhJK2lmRTRjZ0F3SURBUUFCCm8xNHdYREFPQmdOVkhROEJBZjhFQkFNQ0FRWXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QWRCZ05WSFE0RUZnUVUKdVhzL09tWk9LZks2UVNHODc2TUtyYlBOSFpZd0dnWURWUjBSQkJNd0VZSVBkbUZuY21GdWRDOXdhMmt2WkdWNApNQTBHQ1NxR1NJYjNEUUVCQ3dVQUE0SUJBUUFxSEhKek4xK0hyOUNSanJqNnQvczJOYTBlcXBzUFBvbzFuZ0p0CktaWFlOVXNPYzVSbDdLVXpIQXhJamhyaDIwbUFCcEFLTHBVZzNHQ0hwUjRXVTY5K0dyalBFVUpJbmRneit5MVMKS0VNTTEwZWVaQzlxQVRaVVZxdlU0K0ZZM2lBREhibnpKL1ArNU5jdHI4eVRUWlh2MHVwTHdVVHI2aXpVSkluVwpxUjdhbUtuaWZKYU1KZGxpZGQzQVlmYWFtdjlRSkRQU3Z4TWJiOUFha0tzdE94YU1JZWlndFV1MENsK0VVQmpjCmU0V2pKVHdxd1lMc21QNmVtZVgxSHBid0xMTU1OVWRJT29ocm1QYk1KbE5YMUF4aHZOQ05aT21XSDlEbXgrMWMKQWYyeFVZWFlPeUZnV3ZBTzdPZEY2V3UvU3Y3K0FXTFI3QVJJd0VjMXpWcnRScTE1Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0=
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURVakNDQWpxZ0F3SUJBZ0lVYndZSjVDNkFENExqM3VSVTZ3Y0JBUkVKS2Fjd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0dqRVlNQllHQTFVRUF4TVBkbUZuY21GdWRDOXdhMmt2WkdWNE1CNFhEVEUyTVRJeE16QTBNVEV6TWxvWApEVEUzTURFeE1qQTBNVEl3TWxvd0ZURVRNQkVHQTFVRUF4TUtLaTVzYjJOaGJDNXBiekNDQVNJd0RRWUpLb1pJCmh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTWg2VnIyNlFpYUw3U3phMURLVnE3SnA2bjBjcEthMjZSYXEKcDB1OVN5ZHl3dXpVNEc3QWMrYTdueEFVREQwK0J6ZktSTkxCeU43c0RkOUp3b3BDMkphRkJyd3N6ZVFrTFFoNQpCZmlaaHZVT1phMFYxa2IyM2lXNWVGOWszOVpYZHpMWnR6UDNRREdWVGFYb0ZxV0VDdGc2UmR2RUVGOHJFZDlZCjQ1T0JLRTJwMVdkS25UR05PcHljU3FFckhnQlJOTjVqSEJUWDlNdlhORjBPY3UxeWF0N2dGeDlnRUVDcFAxYS8KazJFSko4VUZKT1JSZ0VNR05tUlNwNnJ1aklCRnplN084SCt2Y2plMVp5Z0NFTklScmsvcjU2NWZOUGcwMEFJaQpCQytOSGJiUnhGUnY4dkRDeWd2N2k5eG5rL3cwSXFDTEk4bUhWT3BQVHZ1S0dPWlJQMjhDQXdFQUFhT0JsRENCCmtUQU9CZ05WSFE4QkFmOEVCQU1DQTZnd0hRWURWUjBsQkJZd0ZBWUlLd1lCQlFVSEF3RUdDQ3NHQVFVRkJ3TUMKTUIwR0ExVWREZ1FXQkJRbWd1NTRhUmJZYW83TU5IUkllUmNsZGlLd1VEQWZCZ05WSFNNRUdEQVdnQlM1ZXo4NgpaazRwOHJwQklienZvd3F0czgwZGxqQWdCZ05WSFJFRUdUQVhnZ29xTG14dlkyRnNMbWx2Z2dsc2IyTmhiR2h2CmMzUXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBSVduN2ZLZEhOTzQvTVlTamZwU2xIYUYyMzRzbTNhUnpIQ1YKZFdiaDh2enlBdm91aHUzaUNldXJ4d0gyOUZLTXBxaUJGZlFsclZESG5hTGpjM3UzV2hScFJITTBMaHBaNFBFQQpXZVRGZUtKSkFkcmF2a2crV2V4R2UzNGxncFdUMnJXV3RuVzVrRCtVZnJuVUJWL2I0YlZVeUJSWnd6ZGNJUzhMCmY2VWp0N2lRU1JHZVE1NXZyOFpnMkdQajVjRFh3d2VKUE5sZFhNQWZzTU5yL3JxU0dSVFZRWm51VjJHcDdTTlYKenRyeGRlbU9oeDhRc1BUWnZpWXdqUld1T09ua29Scmc1cSsrYjZvODZCc1UvOUU2aDNieEVmeXNFN29VSkN0RApXeHl0SGF2L3I0bVI0VmxmQzdRazdtNlVFUHhoZTlLUTIvNk5xdHpLZEVvVFVRclFERHM9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0=
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBeUhwV3ZicENKb3Z0TE5yVU1wV3JzbW5xZlJ5a3ByYnBGcXFuUzcxTEozTEM3TlRnCmJzQno1cnVmRUJRTVBUNEhOOHBFMHNISTN1d04zMG5DaWtMWWxvVUd2Q3pONUNRdENIa0YrSm1HOVE1bHJSWFcKUnZiZUpibDRYMlRmMWxkM010bTNNL2RBTVpWTnBlZ1dwWVFLMkRwRjI4UVFYeXNSMzFqams0RW9UYW5WWjBxZApNWTA2bkp4S29Tc2VBRkUwM21NY0ZOZjB5OWMwWFE1eTdYSnEzdUFYSDJBUVFLay9WcitUWVFrbnhRVWs1RkdBClF3WTJaRktucXU2TWdFWE43czd3ZjY5eU43Vm5LQUlRMGhHdVQrdm5ybDgwK0RUUUFpSUVMNDBkdHRIRVZHL3kKOE1MS0MvdUwzR2VUL0RRaW9Jc2p5WWRVNms5Tys0b1k1bEUvYndJREFRQUJBb0lCQUYrUGFSOWcxRDFaZjRGZApBYjdtOXdQQlZ1T3lMbzNGTEZBQW9tUUk0L1QyMEJGaDIyVVBXVy9IU1NlNTFxZXVsSFEwZHgvYS9TdTlhMU5lCjdsdEhSOFJmdm5rZUJqcFVRQjhFeVNMWjA2bWw1ak5kOEZpOVBlRFBpcUEyRGpnMlV2d3JLUmVkS0wwNXhOeHIKUjdnM3U0K2NIMGFGSzZTaGZCQnhaM0VkSkovM2xxcG5za2RVMjBRSXZhUlR6STNOaW01aE1yOEhpUnUyMllYbwoxUEk2b3ZBMmt2RXFtaGx3STgzTDN6dUZRUGRuSTRlcnJ1N3E2OFJjMHJOWERFb3ZxNTFraFVyc3pEeE1JdG1SCnQ1UStmVGVSbVhzV2FJSnUwSm5FazlOcFF0WGRKekxpSUIzenVhU01hRUpYS2lveVFYRXo0VFdlMUdXNHFqeXEKUEI1bVQva0NnWUVBMEpQVVo2VlhWZ1RTRzJnT3NKRE9qREFIR2NDT3RjaWw5WjVZVVRxVXo5TEx5TmtKRWpiSQpIa1FycUhsOXkrdmt1MkRpdlA2dEY5QndueFpaQnRpZGVNOUt5b2VZQlI4Szg3QzFBdEIrb3BsVnpmWGNWdlVhCjFKczUvSU5FWHBlQ1E5Wmcya2o4T1hTZHdydTE5V25DMytuWEpSNjBacndraUlTVktvVlZVU1VDZ1lFQTlnOFQKbWt1ZUNXNEphem00MkI2dTkzdlhTcnFyc3NlUkZSTnhrd3pDUGRiOUdMa3JsdzJiS3QvSjMxckxFZXpHN3NuVApNYjdZc1JtUng4NkVDWWlFYnE2MFRkVmt4S1pUNTFYK0NkWFVYUWZVK0tIaTB3Nk9Kd2JhU0VQaGNKa1A0bS80CkpIYXNWaGdNMnNQaUh1enhleER2TVBhZ1ZjUnh3bnF3bEZRSVhBTUNnWUJLcDI3Ui9pTUpYY1phR3QrUElQVmMKeGQvMHZyQVZycENBSGtIY0tReVVhZzJZZ040M1Q3Wkc1djE5V3FiRTgxUzJJSkpuTlB4OVZwVEl6RFhuTm1iKwprNnRnWERIME8wMHZOZU5EODU0djBwUWNtTkJacTNjRCs5OUFXemVBWjlndk1hOE8waXE4NGRtSmxxZ2xBOHJGClhDd3VWQlFiNVdGcUg1SklXdHJUcFFLQmdFOThrVldQeGU2LzZEVUdRWXMzWmtnMmJsY0t0SHFkYzJXK2tUcnkKclREeTZYSDZKM1cxaElHMkoyMkswL3puWTJBeVBKSmVWM3ZtaWF4bEwwd3hHSzcwcXZSVjBpYWdvSXdqd0Z3SApBb0pIREdxQlNWZnE1TXNBc0xVVmtKY2lLdnA0TjAzNE5EWGZzUTllcGdaZGZxakYwSzhkakxBSU5NT2hoTGQxCjZmbG5Bb0dCQUs1dTIxYzdqS2ppekRlUGp6ODRGRWRSanphZ2VaTnFjbjZhTnk5RVBZQ29Tb05DRkFSWDZMa3MKMi9FRTdIdWNmVytaVVYxc0orS0gvZFlYK2dhd2RIeFhnRkVkclFBQnpMQUZ4K1FpVTZ3VXpCTWt4ZENZSWMxRQo1Ym15eEd6NUJhL3dvZHphb1RqenRaVXdSZkpCMi9qZkt3WGF2bDgvMzdmVFBjVUFtM2tKCi0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0t

---
apiVersion: v1
kind: Secret
metadata:
  name: banking-goose.github
type: Opaque
data:
  client-id: NTQ3YjRhYjA3M2I0ZTM5OGQ0ZjA=
  client-secret: MjYzN2Y3OTMyMTNlMmI4ZDZlM2RlM2Y0YWU2NzUzMTVhOWMzZWVkMQ==


---
apiVersion: v1
kind: Secret
metadata:
  name: banking-goose.google
type: Opaque
data:
  client-id: ODc2MDc2NjM5NDQ0LW8zdTIzZjY5ZGlsdXMxYTBkNzd0ZHQxb3FzMWZpaDViLmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29t
  client-secret: dUVJa1lBMEVxS3dzeEgwdGJMXzY4aUhN 

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: banking-goose
data:
  config.yaml: |
    issuer: https://kube-1.local.io:30443

    storage:
      type: kubernetes
      config:
        inCluster: true

    web:
      https: 0.0.0.0:443
      tlsCert: /etc/dex/tls/tls.crt
      tlsKey: /etc/dex/tls/tls.key

    connectors:
    - type: mockCallback
      id: mock
      name: Example
    - type: github
      id: github
      name: GitHub
      config:
        clientID: $GITHUB_CLIENT_ID
        clientSecret: $GITHUB_CLIENT_SECRET
        redirectURI: https://kube-1.local.io:30443/callback
    - type: oidc
      id: google
      name: Google
      config:
        issuer: https://accounts.google.com
        clientID: $GOOGLE_CLIENT_ID
        clientSecret: $GOOGLE_CLIENT_SECRET
        redirectURI: https://kube-1.local.io:30443/callback

    oauth2:
      skipApprovalScreen: true

    staticClients:
    - id: example-app
      redirectURIs:
        - https://kube-1.local.io:30080/callback
      name: 'Example App'
      secret: ZXhhbXBsZS1hcHAtc2VjcmV0

    enablePasswordDB: true
    staticPasswords:
    - email: "admin@example.com"
      hash: "$2a$10$33EMT0cVYVlPy6WAMCLsceLYjWhuHpbz5yuZxu/GAFj03J9Lytjuy"
      username: "admin"
      userID: "08a8684b-db88-4b73-90a9-3cd1661f5466"
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: banking-goose
  labels:
    app: banking-goose
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: banking-goose
    spec:
      containers:
      - name: banking-goose
        image: quay.io/coreos/dex:v2.0.0-beta.1
        imagePullPolicy: Always
        command: ["/usr/local/bin/dex", "serve", "/etc/dex/cfg/config.yaml"]
        ports:
        - name: https
          containerPort: 443

        volumeMounts:
        - name: config
          mountPath: /etc/dex/cfg
        - name: tls
          mountPath: /etc/dex/tls

        env:
        - name: GITHUB_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: banking-goose.github
              key: client-id
        - name: GITHUB_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: banking-goose.github
              key: client-secret
        - name: GOOGLE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: banking-goose.google
              key: client-id
        - name: GOOGLE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: banking-goose.google
              key: client-secret                
        resources:
          limits:
            cpu: 512m
            memory: 200Mi
          requests:
            cpu: 512m
            memory: 200Mi
      volumes:
      - name: config
        configMap:
          name: banking-goose
          items:
          - key: config.yaml
            path: config.yaml
      - name: tls
        secret:
          secretName: banking-goose.tls            

