apiVersion: v1
kind: Config
clusters:
- name: vagrant
  cluster:
    certificate-authority: /opt/kubernetes/pki/kube-ca.pem
    server: https://kube-apiserver.vm
users:
- name: kube-proxy
  user:
    client-certificate: /opt/kubernetes/pki/kube-proxy-cert.pem
    client-key: /opt/kubernetes/pki/kube-proxy-key.pem
contexts:
- context:
    cluster: vagrant
    user: kube-proxy
  name: kube-proxy
current-context: kube-proxy 
