kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1alpha1
metadata:
  name: scheduler-role-binding
subjects:
  - kind: User
    name: kube-scheduler
roleRef:
  kind: ClusterRole
  name: cluster-admin-all
  apiVersion: rbac.authorization.k8s.io/v1alpha1
