issuer: https://laptop.local.io:5554
storage:
  type: sqlite3
  config:
    file: dex.db
web:
  https: 0.0.0.0:5554
  tlsCert: pki/dex-cert.pem
  tlsKey: pki/dex-key.pem
staticClients:
- id: example-app
  redirectURIs:
  - 'http://laptop.local.io:5555/callback'
  name: 'Example App'
  secret: ZXhhbXBsZS1hcHAtc2VjcmV0
  scopes: groups
connectors:
- type: oidc
  id: google
  name: Google
  config:
    issuer: https://accounts.google.com
    clientID: 876076639444-5f2tgf1nnp70bnov3ak65u3dgr6beg55.apps.googleusercontent.com
    clientSecret: kUQWYcWxT0qh38owT1C_dmgn
    redirectURI: https://laptop.local.io:5554/callback
enablePasswordDB: true
staticPasswords:
- email: "admin@example.com"
  hash: "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W"
  username: "admin"
  userID: "08a8684b-db88-4b73-90a9-3cd1661f5466"
