apiVersion: v1
kind: ReplicationController
metadata:
  name: vault
  namespace: kube-system
spec:
  replicas: 1
  selector:
    app: vault
  template:
    metadata:
      labels:
        pool: vaultpool
        app: vault
    spec:
      containers:
        - name: vault
          image: 'keyolk/vault:0.5.2'
          imagePullPolicy: Always
          args:
          # command = "/usr/bin/run.sh"
            - master
          env:
            - name: "VAULT_DEBUG"
              value: "true"
            - name: "CONSUL_SERVICE_HOST"
              value: "consul.kube-system.svc.cluster.io"
            - name: "CONSUL_SERVICE_PORT_HTTPS"
              value: "8500"
            - name: "CONSUL_SCHEME"
              value: "http"
            - name: "VAULT_SSL_KEY"
              valueFrom:
                secretKeyRef:
                  name: vault-secret
                  key: "tls.key"
            - name: "VAULT_SSL_CRT"
              valueFrom:
                secretKeyRef:
                  name: vault-secret
                  key: "tls.crt"
          readinessProbe:
            httpGet:
              path: /v1/sys/health
              port: 80
            initialDelaySeconds: 10
            timeoutSeconds: 1
          ports:
            - containerPort: 443
              name: vaultport
            - containerPort: 80
              name: vaulthttpport
