apiVersion: v1
kind: Service
metadata:
  name: vault
  labels:
    app: vault
spec:
  ports:
    - name: vault
      port: 8200
  selector:
    app: vault
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: vault
  name: vault
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: vault
    spec:
      containers:
      - image: vault:0.6.2
        name: vault
        ports:
        - containerPort: 8200
          name: vaultport
          protocol: TCP
        env:
        - name: VAULT_DEV_ROOT_TOKEN_ID
          value: vault-root-token