---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1alpha1
metadata:
  name: proxy
subjects:
  - kind: User
    name: kube-proxy
roleRef:
  kind: ClusterRole
  name: proxy
  apiVersion: rbac.authorization.k8s.io/v1alpha1
