---
apiVersion: v1
kind: Service
metadata:
  name: keycloak-db
spec:
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
  selector:
    name: postgres-pod
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak-web
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
    - name: https
      port: 443
      targetPort: 8443
  selector:
    name: keycloak-pod
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - image: postgres
          ports:
            - name: postgres
              containerPort: 5432
          env:
            - name: POSTGRES_DATABASE
              value: keycloak
            - name: POSTGRES_USER
              value: keycloak
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_ROOT_PASSWORD
              value: password
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - image: jboss/keycloak-ha-postgres
        env:
        - name: POSTGRES_DATABASE
          value: keycloak
        - name: POSTGRES_USER
          value: keycloak
        - name: POSTGRES_PASSWORD
          value: password
        ports:
        - containerPort: 8080
        - containerPort: 8443
