apiVersion: v1
kind: Config
clusters:
- name: vagrant
  cluster:
    certificate-authority: /opt/kubernetes/pki/kube-ca.pem
    server: https://kube-apiserver.vm
users:
- name: kube-controller-manager
  user:
    client-certificate: /opt/kubernetes/pki/kube-controller-manager-cert.pem
    client-key: /opt/kubernetes/pki/kube-controller-manager-key.pem
contexts:
- context:
    cluster: vagrant
    namespace: kube-system
    user: kube-controller-manager
  name: kube-controller-manager
current-context: kube-controller-manager 
