apiVersion: v1
kind: Config
clusters:
- name: vagrant
  cluster:
    certificate-authority: /opt/kubernetes/pki/kube-ca.pem
    server: https://kube-apiserver.vm
users:
- name: kube-scheduler
  user:
    client-certificate: /opt/kubernetes/pki/kube-scheduler-cert.pem
    client-key: /opt/kubernetes/pki/kube-scheduler-key.pem
contexts:
- context:
    cluster: vagrant
    namespace: kube-system
    user: kube-scheduler
  name: kube-scheduler
current-context: kube-scheduler
